//modelamos cada rol con sus politicas asociadas

export type ROLES =
    | "ADMINISTRADOR"
    | "AGENTE_INMOBILIARIO"
    | "GESTOR_INMOBILIARIO"
    | "REPRESENTANTE_LEGAL"
    | "RESIDENTE"
    | "FAMILIAR"
    | "OCUPANTE_AUTORIZADO"
    | "INVITADO"
    | "SOPORTE_OPERATIVO"
    | "PERSONAL_MANTENIMIENTO"
    | "TECNICO"
    | "ELECTRICISTA"
    | "PLOMERO"
    | "PERSONAL_LIMPIEZA"
    | "JARDINERO"
    | "SEGURIDAD"
    | "CONSERJE";

export type POLICY_STATEMENT =
    | "VER_INMUEBLE"
    | "EDITAR_INMUEBLE"
    | "ELIMINAR_INMUEBLE"
    | "VER_DOCUMENTOS_INMUEBLE"
    | "SUBIR_DOCUMENTOS_INMUEBLE"
    | "VER_CONTRATOS"
    | "REGISTRAR_CONTRATOS"
    | "EDITAR_CONTRATOS"
    | "ELIMINAR_CONTRATOS"
    | "RENOVAR_CONTRATOS"
    | "FINALIZAR_CONTRATOS"
    | "SUSPENDER_CONTRATOS"
    | "DESCARGAR_CONTRATOS"
    | "VER_DOCUMENTOS_CONTRATO"
    | "SUBIR_DOCUMENTOS_CONTRATO"
    | "ELIMINAR_DOCUMENTOS_CONTRATO"
    | "VER_HISTORIAL_CONTRATO"
    | "VER_CONTRATOS_PRELIMINARES"
    | "CONSULTAR_SERVICIOS_PUBLICOS"
    | "REGISTRAR_SERVICIO_PUBLICO"
    | "EDITAR_SERVICIO_PUBLICO"
    | "ELIMINAR_SERVICIO_PUBLICO"
    | "CONSULTAR_FACTURAS_SERVICIOS_PUBLICOS"
    | "REGISTRAR_FACTURA_SERVICIO_PUBLICO"
    | "EDITAR_FACTURA_SERVICIO_PUBLICO"
    | "ELIMINAR_FACTURA_SERVICIO_PUBLICO"
    | "CONSULTAR_CONSUMOS_SERVICIOS_PUBLICOS"
    | "REGISTRAR_LECTURA_SERVICIO_PUBLICO"
    | "EDITAR_LECTURA_SERVICIO_PUBLICO"
    | "CONSULTAR_PAGOS_SERVICIOS_PUBLICOS"
    | "REGISTRAR_PAGO_SERVICIO_PUBLICO"
    | "EDITAR_PAGO_SERVICIO_PUBLICO"
    | "DESCARGAR_FACTURAS_SERVICIOS_PUBLICOS"
    | "VER_HISTORIAL_SERVICIOS_PUBLICOS"
    | "CONSULTAR_INFORMACION_LEGAL"
    | "REGISTRAR_INFORMACION_LEGAL"
    | "EDITAR_INFORMACION_LEGAL"
    | "ELIMINAR_INFORMACION_LEGAL"
    | "CONSULTAR_DOCUMENTOS_LEGALES"
    | "SUBIR_DOCUMENTOS_LEGALES"
    | "DESCARGAR_DOCUMENTOS_LEGALES"
    | "ELIMINAR_DOCUMENTOS_LEGALES"
    | "CONSULTAR_HISTORIAL_LEGAL"
    | "CONSULTAR_INVITACIONES_MIEMBROS"
    | "ENVIAR_INVITACION_MIEMBRO"
    | "REENVIAR_INVITACION_MIEMBRO"
    | "CANCELAR_INVITACION_MIEMBRO";

interface RolesAndPoliciesStatements {
    role: ROLES;
    policies: POLICY_STATEMENT[];
}

export const ROLES_AND_POLICIES: RolesAndPoliciesStatements[] = [
    {
        role: "ADMINISTRADOR",
        policies: [
            "VER_INMUEBLE",
            "VER_DOCUMENTOS_INMUEBLE",
            "VER_CONTRATOS",
            "DESCARGAR_CONTRATOS",
            "VER_DOCUMENTOS_CONTRATO",
            "VER_HISTORIAL_CONTRATO",
            "VER_CONTRATOS_PRELIMINARES",
            "CONSULTAR_SERVICIOS_PUBLICOS",
            "CONSULTAR_FACTURAS_SERVICIOS_PUBLICOS",
            "CONSULTAR_CONSUMOS_SERVICIOS_PUBLICOS",
            "CONSULTAR_PAGOS_SERVICIOS_PUBLICOS",
            "DESCARGAR_FACTURAS_SERVICIOS_PUBLICOS",
            "VER_HISTORIAL_SERVICIOS_PUBLICOS",
            "CONSULTAR_INFORMACION_LEGAL",
            "CONSULTAR_DOCUMENTOS_LEGALES",
        ],
    },
];
